### ISSUE TITLE
Issues with paired analysis table

### ISSUE THREAD

**Issue by kariljordan** [kariljordan/assessment-fork#12]
In code chunk 494 we have a paired analysis table (t-test) to compare pre and post scores for perception of tools.

Jonah mentioned that we cannot treat likert scaled items as continuous variables. He said the neutral-centered likert graphs are really a fantastic way to visualize this kinda data. He also recommended checking [this out](https://www.st-andrews.ac.uk/media/capod/students/mathssupport/Likert.pdf) to get help with how to show this type of data.

Erin also suggested that we have the p-values show up in scientific notation to avoid it looking like there is a p-value of 0.

**Comment by kariljordan** [comment]
Three issues:

1. Is it appropriate to average scoring from a strongly disagree (1) to strongly agree (5)? Can we make an average of this number? It's an ordinal scale, not a continuous scale. Is it ok when we use paired data?
2. Is a t-test appropriate, or should we switch to a non-parametric test?

**Comment by tracykteal** [comment]
Agree there are potential issues with this approach to analysis. I think in these sections add info on how the analysis was done, and acknowledge there are other approaches.

**Comment by kariljordan** [comment]
Added [here](https://github.com/kariljordan/assessment-fork/commit/a931fbf596061b1c05960ec0632577b14778541b). @fmichonneau can you add in-line text for the number of paired responses we have? Right now it says "This figure includes XX responses."

**Comment by fmichonneau** [comment]
I added the numbers of responses inline with cd2c9ab
