### ISSUE TITLE
Neutral centered graphs

### ISSUE THREAD

**Issue by kariljordan** [kariljordan/assessment-fork#13]
I created a neutral centered graph for the pre-workshop perception scores (Line 661-722) and the post-workshop perception scores. I'm interested in how to put these plots together (in a grid?) so that we can visually see the shift in pre/post scores.

Lastly, this is the plot of all the data. How can we do a plot like this with only the data from those who gave their unique ID pre and post?

**Comment by kariljordan** [comment]
@fmichonneau had the idea of making a histogram. Will come back to this later.

**Comment by fmichonneau** [comment]
I put something in, let me know if it's what you had in mind.

**Comment by kariljordan** [comment]
Yes! When we meet next week I'll get you to explain the distribution plot. I think I understand it but I want to make sure. Also, the post-workshop neutral centered plot includes the feedback about the instructors. I'm not sure how to fix that.

**Comment by kariljordan** [comment]
There are issues with the negative scores. We need to put in the text that people read the question wrong.

**Comment by kariljordan** [comment]
Closed per [this commit](https://github.com/kariljordan/assessment-fork/commit/a931fbf596061b1c05960ec0632577b14778541b)
