### ISSUE TITLE
Mode

### ISSUE THREAD

**Issue by kariljordan** [kariljordan/assessment-fork#27]
@fmichonneau Since we can't report the mean of the responses for paired data since it's on a scale of 1-5, can we show the mode pre and the mode post?

**Comment by fmichonneau** [comment]
I updated the code to use the mode. Given that it's a discrete distribution, I used the basic approach of finding the most common value in the distribution. If there are ties, the lowest score is chosen.

I am not convinced this visualization makes sense when using discrete values. I think I understand reservations about using the mean on ordinal values (and comparing them), but I think the change in average on paired data reflects our impact.

If using the means is really not an option, then we can remove this visualization, and use the graph underneath. I also added another graph that shows the distributions of the scores before and after the workshop for each skill.

**Comment by kariljordan** [comment]
Hi @fmichonneau. This is FANTASTIC. I am in agreement with you that the mean should still be an option, but it looks like from this figure the mode may actually work. Did you notice that for Write Program, Search Online, Raw Data, and Overcome Problem we only have a dot for the pre-workshop score?

I really like the graph you added underneath that shows the distribution before and after. I actually understand this a bit better--meaning, it didn't take me as long to understand it as the one underneath. Can we change this so that it shows the percentages on the Y axis with counts above the bars?

**Comment by kariljordan** [comment]
And I assumed that but wanted to make sure. Yes, I think the mean shows much more of an impact. Can we put both in the report and then once we bring the report to the assessment team we can discuss all of the figures and decide what to keep and what to omit?

**Comment by fmichonneau** [comment]
I realized that the mean is reported in the likert heatmaps, so if we decide that means are not an appropriate way to summarize these results, we need to edit the plots to remove the means from there as well.

**Comment by kariljordan** [comment]
Once we're done and bring this report to the rest of the team I'd like to revisit the **mean** discussion. I agree though. I noticed the mean was showing in the heat map.

**Comment by kariljordan** [comment]
Closing this as we decided to go with the mean dot plots and neutral centered graphs.
