### ISSUE TITLE
Likert plot for perception of helpers mislabeled

### ISSUE THREAD

**Issue by kariljordan** [kariljordan/assessment-fork#28]
The plot for perception of SWC helpers has the following labels:

- ClearAnswers
- Enthusiastic
- Communicators
- Teamwork

The labels should be the same as the perception of instructors, and the order should be
- Considerate
- Enthusiastic
- Clear Answers
- Teamwork

**Comment by fmichonneau** [comment]
in the likert plot, the categories are arranged in decreasing order of the rate of positive answers. I don't know if it's going to be easy to change.

I did rename the helper column so it matches the one used for the instructors

**Comment by kariljordan** [comment]
Ok we won't worry about changing that. Thanks!
