### ISSUE TITLE
Axes label order for Effect of Workshops on Learners Self-Reported Perspectives

### ISSUE THREAD

**Issue by kariljordan** [kariljordan/assessment-fork#29]
I'd like the order for all of the plots for Data Carpentry under *Effect of Workshops on Learners Self-Reported Perspectives: Skills & Confidence* to be:

- Write Program
- Search Online
- Raw Data
- Programming Efficient
- Programming Confident
- Overcome Problem
- Analyses Easier

I also want to make sure there are spaces between all the words in the axis labels.

Lastly, is there a way to show *n* for each of these plots? And is there a way to plot the aggregate and also only the data from those who gave their unique ID and did the pre/post?

**Comment by fmichonneau** [comment]
let's revisit this once we settle on the visualizations that will be included in the report.

**Comment by kariljordan** [comment]
We will use the mean dot plot and the neutral centered plots, so can we make sure the neutral centered plot has the axis labels ordered as above?
