### ISSUE TITLE
Aesthetics

### ISSUE THREAD

**Issue by kariljordan** [kariljordan/assessment-fork#30]
- [x] Make sure the numbers above the bar charts are spaced so that they don't sit inside the bar chart.
- [x] Make sure that all axes labels have spaces in between the words.
- [x] Consider a consistent color scheme for the plots. Should we switch to the colors that are in the Likert plot? I don't know if changing those colors is an option.

**Comment by fmichonneau** [comment]
I'd like to suggest we use lollipop plots instead of bar plots. I included one for the DC workshop attended (the 1st graph in the report). I think they look better than the bar plots, and flipping the axis means we have more room for the labels. @kariljordan what do you think?

**Comment by kariljordan** [comment]
The lollipop plots look MUCH BETTER! I'm a fan of using these throughout.
