### ISSUE TITLE
Order of bars in SWC ability plots

### ISSUE THREAD

**Issue by kariljordan** [kariljordan/assessment-fork#31]
I would like the order of the bar charts for SWC in the *Respondent Ability to Perform Computing Tasks* to be:

- Pipes Ability
- Loops Ability
- Git Ability
- Function Ability
- Import Library Ability
- Unit Test Ability
- SQL Query Ability

Also, can we rename these to remove the word *Ability* from each?

**Comment by fmichonneau** [comment]
done!
