### ISSUE TITLE
Gender/Ethnicity tables

### ISSUE THREAD

**Issue by kariljordan** [kariljordan/assessment-fork#33]
I would like for the Gender and Ethnicity tables for DC and SWC to show the highest percentage at the top and lowest on the bottom. Also, the DC tables have decimals in the figures, and the SWC tables are whole numbers. I'd like both tables to have decimals if possible.

**Comment by fmichonneau** [comment]
all tables are now formatted the same way (arranged in decreasing order of "n", the percentages displayed with one decimal)
