### ISSUE TITLE
Filtering survey results data quality

### ISSUE THREAD

**Issue by fmichonneau** [kariljordan/assessment-fork#35]
Because of the way the data is structured, we can't ignore empty cells when doing tallies. It means we may want to filter out some rows because respondents didn't fill many answers. A few ways of doing this would be:

- filtering any answer where the respondent didn't fill the uniqueID
- deciding on a minimum number of questions the respondent would have answered to include their answer
- for each question, removing rows where the respondent didn't answer

**Comment by fmichonneau** [comment]
going with the last option at least for now

**Comment by kariljordan** [comment]
I am a fan of the last option.

**Comment by fmichonneau** [comment]
I'm going to close this one. We can re-open issues for specific parts of the report as needed.
