### ISSUE TITLE
variable not analyzed?

### ISSUE THREAD

**Issue by fmichonneau** [kariljordan/assessment-fork#37]
it looks like the "perception" of tools variables in SWC post data are not being analyzed (e.g., ShellPerception, GitPerception, etc.). Is it normal?

**Comment by kariljordan** [comment]
Yes, we decided in the in-person meeting with @tracykteal that we would not include these. We can revisit if you think reporting out on those variables will be helpful, but we won't include those questions in the common survey.

**Comment by fmichonneau** [comment]
OK, that sounds good.
