### ISSUE TITLE
transgender male not displayed

### ISSUE THREAD

**Issue by fmichonneau** [kariljordan/assessment-fork#38]
with current code, only variables with at least 1 observation get displayed and therefore "transgender male" isn't listed in the results. Leave as is, or add row with value of 0?

**Comment by kariljordan** [comment]
If we add a row of value 0, if we have more values later, will it automatically be added? Or will we need to change the code to show the value if we have values come in in the future?

**Comment by fmichonneau** [comment]
I can code it such that if we do have values in the future the count would show instead of 0

**Comment by kariljordan** [comment]
Perfect, let’s do that please.

**Comment by fmichonneau** [comment]
done
