### ISSUE TITLE
Number of workshops

### ISSUE THREAD

**Issue by kariljordan** [kariljordan/assessment-fork#4]
In the [template report draft code](https://github.com/kariljordan/assessment-fork/blob/gainseville/learner-assessment/template_report_draft.rmd) we are going to provide the number of workshops the data set covers, but we don't have that in this data. We'd need to pull that information from AMY, or filter the slugs from the raw data located in the [private data repo](https://github.com/carpentries/private-data/tree/master/learner-assessment). Thoughts?

**Comment by kariljordan** [comment]
@fmichonneau will look at this later. It requires running a query in AMY.

**Comment by tracykteal** [comment]
I think it's OK to include just the number of responses in this report, and link to the programmatic assessment that has the info on number of workshops.

**Comment by kariljordan** [comment]
Thanks Tracy! [Added](https://github.com/kariljordan/assessment-fork/commit/b51d796977ada647e6e6533e865fef923bb67307)
