### ISSUE TITLE
ordering in Data Carpentry text sections

### ISSUE THREAD

**Issue by tracykteal** [kariljordan/assessment-fork#40]
In the sections 

- Data Carpentry Learners satisfaction with current data management practices
- Data Carpentry Learners current programming usage

They are ordered by percentage. It would likely make it easier to read if they were ordered as they are in the question. e.g. Very satisfied, Satisfied ...

**Comment by kariljordan** [comment]
Fix [here](https://github.com/kariljordan/assessment-fork/commit/0cb801bad45d87efba945ca1e30b6501553c894c)
