### ISSUE TITLE
Erin review (WIP)

### ISSUE THREAD

**Issue by ErinBecker** [kariljordan/assessment-fork#43]
Review comments on Kari's [report](https://github.com/kariljordan/assessment-fork/blob/gainseville/learner-assessment/template_report_draft.rmd).

- [x] List authors? I think it would be good to give credit by name to the authors (primarily Kari and Francois, maybe a few others, but definitely not me!)
- [x] (typo) "begin with a lesson on data organization and includes" should be "include"
- [x] "base programming language" remove "base"
- [x] Change "Data Carpentry’s Genomics curriculum also includes programming, however the focus of this curriculum" to "Data Carpentry's Genomics curriculum focuses on . . . "
- [ ] (formatting) In all of the tables that have an "n" column and a "%" column, the numbers kind of run together and it's hard to see where one column stops and the next starts. Is there an easy way of fixing this formatting? Adding a divider bar between the columns or increasing the spacing between columns? @fmichonneau 
- [x] For the paragraph introducing SWC curriculum, maybe something like "Software Carpentry’s curriculum teaches basic lab skills for scientific computing. Their workshops includes automation with the Unix shell, version control with Git, and programming with R or Python. These tools help learners to increase the efficiency and reproducibility of their computational work."
- [x] I recommend not showing the table titled "Data Carpentry Learners satisfaction with current data management practices", as the information is also found in the subsequent graphic.
- [x] "or feel neutral about being satisfied" to "or neutral" (take out "about being satisfied")
- [x] Can the table titled "Data Carpentry Learners current programming usage" be removed in favor of a graphic like the one for the satisfaction with data management practices? That graphic is much easier to interpret at a glance than the table.
- [x] "as Data Carpentry workshops tend to attract novices." to "as Data Carpentry workshops are intended for novices."
- [x] "79% of Data Carpentry respondents either agree or strongly agree that they felt comfortable learning in their workshop environment, and 87.1% of Software Carpentry’s respondents agreed or strongly agreed the workshop atmosphere was welcoming." YAY!!!!!!! :carpentries: This definitely needs to be in a tweet!
- [x] "We would like to explore what training would help our instructors so that the percentage of respondents who felt they were able to get clear answers to their questions from the instructors would increase." maybe note that this was still a very good score.
- [x] "it is great to see that 47.2% of learners either learned mostly or all new information during the workshop." add "while another XX% learned something new" . . . 
- [x] "After reading the open-ended responses, we see that the issues were related to not being able to hear and/or see in the back of the room." one sentence about what we're going to do about this. This should feed into Instructor Training :-)
- [ ] "77.6% of Data Carpentry respondants who answered this question are promoters (i.e. would recommend a workshop). For Software Carpentry respondents who answered this questions, 56.9% are promoters." Numbers don't match table. Is the table a composite of SWC and DC? If so change title.
~~- [ ] For the "Pre and Post Comparison of Skills and Perception" graphic, not every line has a post-workshop score. Can you explain why in the graphic somewhere?~~
- [x] Actually, I would probably show only the "mean" version of this graphic and not the "mode" version.
- [ ] (typo) This figure includes XX respondses.
- [ ] (typo) "Contrarily, confidence in using programming to work with data increased from XX% to xx%."
- [x] Near the end of the report, there are two sections where the same data is shown in 2-4 different graphical representations. This may be confusing to readers. I would choose to show only one of these graphics (or at most two). My preference is the neutral centered graphs and the dot plots of means.

--

**Comment by kariljordan** [comment]
@fmichonneau for this

> "77.6% of Data Carpentry respondants who answered this question are promoters (i.e. would recommend a workshop). For Software Carpentry respondents who answered this questions, 56.9% are promoters." Numbers don't match table. Is the table a composite of SWC and DC? If so change title.

I believe it's because the calculation includes the "didn't answer" category. Can you help with fixing that?

**Comment by kariljordan** [comment]
@ErinBecker regarding mean vs. mode, we only added mode because both you and Jonah brought up the issues with ordinals and means/p-values. We've done a lot of reading and talking with you and Tracy, and we've decided to include the mean and tell the reader if they're interested in doing their own analysis to feel free.

**Comment by kariljordan** [comment]
@fmichonneau can you add in-line text for this:

> (typo) This figure includes XX respondses.

It's for the pre- and post-comparison of skills and perception.

**Comment by kariljordan** [comment]
@fmichonneau can you add in-line text for this:

> "Contrarily, confidence in using programming to work with data increased from XX% to xx%."

It's below the distribution for the change in scores plots.

**Comment by kariljordan** [comment]
@ErinBecker regarding this comment:

>  Near the end of the report, there are two sections where the same data is shown in 2-4 different graphical representations. This may be confusing to readers. I would choose to show only one of these graphics (or at most two). My preference is the neutral centered graphs and the dot plots of means.

We have all three in because we planned to bring the report to the data and assessment team to get your feedback about which plots to include, but we've decided to keep neutral centered and dot plots w/means. Thanks! Glad we agree:)

**Comment by ErinBecker** [comment]
> @ErinBecker regarding mean vs. mode, we only added mode because both you and Jonah brought up the issues with ordinals and means/p-values. We've done a lot of reading and talking with you and Tracy, and we've decided to include the mean and tell the reader if they're interested in doing their own analysis to feel free.

Ok, sounds good. Sorry for the mixed messages.

**Comment by ErinBecker** [comment]
> We have all three in because we planned to bring the report to the data and assessment team to get your feedback about which plots to include, but we've decided to keep neutral centered and dot plots w/means. Thanks! Glad we agree:)

Me too!
