### ISSUE TITLE
Two plots with "didn't answer" included

### ISSUE THREAD

**Issue by kariljordan** [kariljordan/assessment-fork#45]
Hi @fmichonneau, I believe I may have asked you to include the "Didn't answer" choices for the two plots under workshop environment, but I'm looking at it now and wondering if it's possible to remove that from the plot and do like you did in the plots above where you say 'Didn't answer not shown'. Thoughts?

Also, can you remove 'Didn't answer' from the first plot under Workshop Type and Perception of Workshop Environment/Experience and say 'Didn't answer not shown'?

Also for the DC plot for being able to immediately apply what they learned at the workshop and the SWC plot for respondents learning mostly new information.

**Comment by fmichonneau** [comment]
thinking about this a little more, I think I prefer to actually display these answers in the graphs. It seems to give a better picture of how our answers are spread out. It would also make the code more complicated to have to deal with both data and calculate the percentages once with the NAs included and once without. So if it's OK with, I'd like to keep "Didn't answer" in the plots.

**Comment by kariljordan** [comment]
That sounds good to me!
