### ISSUE TITLE
DC countries

### ISSUE THREAD

**Issue by fmichonneau** [kariljordan/assessment-fork#52]
looking at the text from the report, it seems that the plot should be interpreted as where the workshop took place. However, I don't think we've ever had a workshop in Afganistan or Albania which makes me think that some learners must have interpreted this question as "where are you from?"

**Comment by fmichonneau** [comment]
Maybe it's best to remove it, and point to the programmatic assessment instead?

**Comment by kariljordan** [comment]
That's a great idea. I don't suppose there's a way to embed the plot from the programmatic report into our report is there?
