### ISSUE TITLE
Open ended responses for accessibility issues

### ISSUE THREAD

**Issue by kariljordan** [kariljordan/assessment-fork#9]
In line 472 we have a code chunk for a table of percentages for those with accessibility issues. We need to explain what the open ended responses say. How can we do this with code?

```{r}
# Table
kable(issues, format = 'markdown', row.names = NA, col.names = c ("Respondents having accessibility issues", "n", "%"))
```

[template report draft](https://github.com/kariljordan/assessment-fork/blob/gainseville/learner-assessment/template_report_draft.rmd)

**Comment by kariljordan** [comment]
@kariljordan will explain with a brief paragraph, from a brief survey of the answers, most of the issues were related to...

**Comment by tracykteal** [comment]
Looks like this has been included, so we can close this issue?
